#!/usr/bin/env node
// ⚡ restforge — OpenAPI → Typed API Client Generator

const fs   = require('fs');
const path = require('path');

const GREEN  = '\x1b[32m'; const YELLOW = '\x1b[33m';
const CYAN   = '\x1b[36m'; const BOLD   = '\x1b[1m';
const DIM    = '\x1b[2m';  const NC     = '\x1b[0m';

// ── TypeScript generator ──────────────────────────────────
function genTypeScript(spec) {
  const { info = {}, paths = {}, components = {} } = spec;
  const schemas = components.schemas || {};
  let out = `// Auto-generated by restforge v1.0.0 — DO NOT EDIT\n// Source: ${info.title || 'OpenAPI Spec'} v${info.version || '1.0'}\n\n`;

  // Generate interfaces from schemas
  for (const [name, schema] of Object.entries(schemas)) {
    out += `export interface ${name} {\n`;
    for (const [prop, def] of Object.entries(schema.properties || {})) {
      const required = (schema.required || []).includes(prop);
      const tsType   = openApiTypeToTS(def);
      const comment  = def.description ? `  /** ${def.description} */\n` : '';
      out += `${comment}  ${prop}${required ? '' : '?'}: ${tsType};\n`;
    }
    out += `}\n\n`;
  }

  // Generate fetch functions from paths
  out += `const BASE_URL = process.env.API_BASE_URL || '';\n`;
  out += `const API_KEY  = process.env.API_KEY || '';\n\n`;
  out += `class APIError extends Error {\n  constructor(public status: number, message: string) { super(message); }\n}\n\n`;

  for (const [routePath, methods] of Object.entries(paths)) {
    for (const [method, op] of Object.entries(methods)) {
      if (!op || typeof op !== 'object') continue;
      const fnName = op.operationId || `${method}${routePath.replace(/[^a-zA-Z]/g,'_')}`;
      const params = (op.parameters || []).filter(p => p.in === 'path');
      const paramStr = params.map(p => `${p.name}: string | number`).join(', ');
      const urlStr = routePath.replace(/\{([^}]+)\}/g, '${$1}');
      const responseType = resolveResponseType(op, schemas);
      const desc  = op.summary ? `/** ${op.summary} */\n` : '';

      out += `${desc}export async function ${camelCase(fnName)}(${paramStr}): Promise<${responseType}> {\n`;
      out += `  const res = await fetch(\`\${BASE_URL}${urlStr}\`, {\n`;
      out += `    method: '${method.toUpperCase()}',\n`;
      out += `    headers: { 'Content-Type': 'application/json', Authorization: \`Bearer \${API_KEY}\` },\n`;
      out += `  });\n`;
      out += `  if (!res.ok) throw new APIError(res.status, await res.text());\n`;
      out += `  return res.json();\n}\n\n`;
    }
  }
  return out;
}

function openApiTypeToTS(def) {
  if (!def) return 'unknown';
  if (def.$ref) return def.$ref.split('/').pop();
  switch (def.type) {
    case 'integer': case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'array':   return `${openApiTypeToTS(def.items)}[]`;
    case 'object':  return 'Record<string, unknown>';
    default:        return 'string';
  }
}

function resolveResponseType(op, schemas) {
  const resp200 = op.responses?.['200']?.content?.['application/json']?.schema;
  if (!resp200) return 'void';
  if (resp200.$ref) return resp200.$ref.split('/').pop();
  if (resp200.type === 'array' && resp200.items?.$ref) return `${resp200.items.$ref.split('/').pop()}[]`;
  return 'unknown';
}

function camelCase(str) {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase()).replace(/^[A-Z]/, c => c.toLowerCase());
}

// ── Python generator ──────────────────────────────────────
function genPython(spec) {
  const { info = {}, paths = {}, components = {} } = spec;
  const schemas = components.schemas || {};
  let out = `# Auto-generated by restforge v1.0.0 — DO NOT EDIT\n# Source: ${info.title || 'API'} v${info.version || '1.0'}\nfrom dataclasses import dataclass\nfrom typing import Optional, List\nimport httpx, os\n\nBASE_URL = os.getenv('API_BASE_URL', '')\nAPI_KEY  = os.getenv('API_KEY', '')\n\n`;

  for (const [name, schema] of Object.entries(schemas)) {
    out += `@dataclass\nclass ${name}:\n`;
    const props = Object.entries(schema.properties || {});
    if (!props.length) out += `    pass\n`;
    props.forEach(([prop, def]) => {
      const pyType = def.type === 'integer' ? 'int' : def.type === 'number' ? 'float' : def.type === 'boolean' ? 'bool' : 'str';
      const required = (schema.required || []).includes(prop);
      out += `    ${prop}: ${required ? pyType : `Optional[${pyType}]`} = None\n`;
    });
    out += '\n';
  }

  out += `\nclient = httpx.Client(base_url=BASE_URL, headers={'Authorization': f'Bearer {API_KEY}'})\n\n`;
  for (const [routePath, methods] of Object.entries(paths)) {
    for (const [method, op] of Object.entries(methods)) {
      if (!op || typeof op !== 'object') continue;
      const fnName  = (op.operationId || `${method}_${routePath.replace(/[^a-z]/gi,'_')}`).toLowerCase();
      const params  = (op.parameters || []).filter(p => p.in === 'path').map(p => p.name).join(', ');
      const pyPath  = routePath.replace(/\{([^}]+)\}/g, '{$1}');
      const summary = op.summary ? `    """${op.summary}"""\n` : '';
      out += `def ${fnName}(${params}):\n${summary}    return client.${method}(f"${pyPath}").json()\n\n`;
    }
  }
  return out;
}

// ── Demo spec ─────────────────────────────────────────────
const DEMO_SPEC = {
  info: { title: 'Users API', version: '1.0.0' },
  paths: {
    '/api/users': {
      get:  { operationId: 'listUsers',  summary: 'List all users',   responses: { '200': { content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/User' } } } } } } },
      post: { operationId: 'createUser', summary: 'Create a user',    responses: { '201': { content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } } } },
    },
    '/api/users/{id}': {
      get:    { operationId: 'getUser',    summary: 'Get user by ID',   parameters: [{ name: 'id', in: 'path' }], responses: { '200': { content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } } } },
      delete: { operationId: 'deleteUser', summary: 'Delete a user',    parameters: [{ name: 'id', in: 'path' }], responses: { '204': {} } },
    },
  },
  components: {
    schemas: {
      User: {
        required: ['id', 'name', 'email'],
        properties: {
          id:        { type: 'integer', description: 'Unique user identifier' },
          name:      { type: 'string',  description: 'Full name' },
          email:     { type: 'string',  description: 'Email address' },
          createdAt: { type: 'string',  description: 'ISO timestamp' },
        },
      },
    },
  },
};

// ── CLI ───────────────────────────────────────────────────
const args   = process.argv.slice(2);
const cmd    = args[0] || 'demo';
const lang   = args[args.indexOf('--lang') + 1] || 'typescript';
const outDir = args[args.indexOf('--out')  + 1] || './generated';

console.log(`\n${CYAN}${BOLD}⚡ restforge — OpenAPI Client Generator${NC}\n`);

if (cmd === 'demo') {
  console.log(`${BOLD}Generating TypeScript client from demo spec...${NC}\n`);
  const ts = genTypeScript(DEMO_SPEC);
  fs.mkdirSync('./generated', { recursive: true });
  fs.writeFileSync('./generated/api-client.ts', ts);
  console.log(`${GREEN}✅ TypeScript client → ./generated/api-client.ts${NC}`);
  console.log(`\n${DIM}Preview (first 20 lines):${NC}\n`);
  ts.split('\n').slice(0, 20).forEach(l => console.log(`  ${DIM}${l}${NC}`));
  console.log('\n');

  console.log(`${BOLD}Generating Python client...${NC}`);
  const py = genPython(DEMO_SPEC);
  fs.writeFileSync('./generated/api_client.py', py);
  console.log(`${GREEN}✅ Python client → ./generated/api_client.py${NC}\n`);

} else if (cmd === 'generate' && args[1]) {
  const specFile = args[1];
  if (!fs.existsSync(specFile)) { console.error(`❌ File not found: ${specFile}`); process.exit(1); }
  const spec = JSON.parse(fs.readFileSync(specFile, 'utf8'));
  fs.mkdirSync(outDir, { recursive: true });
  const code = lang === 'python' ? genPython(spec) : genTypeScript(spec);
  const ext  = lang === 'python' ? 'py' : 'ts';
  const out  = path.join(outDir, `api-client.${ext}`);
  fs.writeFileSync(out, code);
  console.log(`${GREEN}✅ ${lang} client → ${out}${NC}\n`);

} else if (cmd === 'validate' && args[1]) {
  try {
    const spec = JSON.parse(fs.readFileSync(args[1], 'utf8'));
    const issues = [];
    if (!spec.openapi && !spec.swagger) issues.push('Missing openapi/swagger version field');
    if (!spec.info?.title)  issues.push('Missing info.title');
    if (!spec.paths)        issues.push('Missing paths object');
    if (issues.length) { issues.forEach(i => console.log(`${YELLOW}⚠️  ${i}${NC}`)); }
    else console.log(`${GREEN}✅ Spec is valid!${NC}\n`);
  } catch (e) { console.error(`${'\x1b[31m'}❌ Invalid JSON: ${e.message}${NC}`); process.exit(1); }

} else {
  console.log(`Usage:`);
  console.log(`  node src/generator.js demo`);
  console.log(`  node src/generator.js generate openapi.json --lang typescript --out ./src/api`);
  console.log(`  node src/generator.js generate openapi.json --lang python --out ./lib`);
  console.log(`  node src/generator.js validate openapi.json\n`);
}
